# Generated by Django 2.1.2 on 2018-10-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181024_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='descripcionComuna',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='descripcionProvincia',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='region',
            name='descripcionRegion',
            field=models.CharField(max_length=90),
        ),
    ]
